# Comments on
# 1) build
# 2) run
# 3) update

#docker build -t kodi_all:0.1 -f Dockerfile_ubuntu_all .

# outside
#docker run -d -p 0.0.0.0:3003:3003 -p 0.0.0.0:3001:3000 --restart unless-stopped --name kodi_all \
#--env-file .env -v "$(pwd)"/src/data:/iptv/iptv/src/data kodi_all:0.1
##--add-host=host.docker.internal:host-gateway
# locally
##docker run -d -p 127.0.0.1:3003:3003 -p 127.0.0.1:3001:3000 --restart unless-stopped --name kodi_all \
#--env-file .env -v "$(pwd)"/src/data:/iptv/iptv/src/data kodi_all:0.1
# update guide regularly via
# docker exec -w <working dir> <container id | name> npm run grab -- --site=<web site>, e.g.
#docker exec -w /iptv/epg/scripts/commands/epg/ kodi_all npm run grab -- --site=chaines-tv.orange.fr
# crontab -e
#0 9,12,15,18 * * * docker exec -w /iptv/epg/scripts/commands/epg/ kodi_all npm run grab -- --site=chaines-tv.orange.fr

FROM ubuntu:22.04

# iptv service
WORKDIR /iptv/iptv/
COPY src/*.py src/
COPY requirements.txt .

RUN apt-get update \
    && apt-get upgrade -y
RUN apt-get install git -y
RUN apt-get install curl -y
RUN curl -fsSL https://deb.nodesource.com/setup_current.x | bash -
RUN apt-get install nodejs -y \
    && npm update --global npm
RUN apt-get install python3-pip -y \
    && pip install -r requirements.txt \
    && rm -f requirements.txt

WORKDIR /iptv/
COPY wrapper.sh .
RUN ["chmod", "+x", "wrapper.sh"]
RUN git clone --depth 1 -b master https://github.com/iptv-org/epg.git

WORKDIR /iptv/epg/
# 1024 MiB on raspberry Pi 4
ARG MAX_OLD_SPACE_SIZE=1024
ENV NODE_OPTIONS="--max_old_space_size=${MAX_OLD_SPACE_SIZE}"
RUN npm install

ENV IPTV_URL=$IPTV_URL

WORKDIR /iptv/
# web server at
# http://<intranet host name/ip address>:3001/guide.xml
# remapped at
# http://<intranet host name/IP address>:3003/guide.xml
CMD ./wrapper.sh