# update EPG via $ docker exec -w <working dir> <container id | name> npm run grab -- --site=<web site>, e.g.
#docker exec -w /iptv/epg/scripts/commands/epg/ kodi_all npm run grab -- --site=chaines-tv.orange.fr
# via crontab -e 0 9,12,15,18 * * * docker exec -w /iptv/epg/scripts/commands/epg/ kodi_all npm run grab --- --site=tv.blue.ch --maxConnections=3
FROM ubuntu:22.04

# iptv service
WORKDIR /iptv/iptv/
COPY src/*.py src/
COPY requirements.txt .

RUN apt-get update; \
    apt-get -y upgrade
RUN apt-get -y install git
RUN apt-get -y install curl

# see also https://linuxize.com/post/how-to-install-node-js-on-ubuntu-22-04/
ARG NODE_MAJOR=24
RUN apt-get install -y ca-certificates libatomic1 gnupg; \
    mkdir -p /etc/apt/keyrings; \
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key \
     | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg; \
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] \
    https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" \
     > /etc/apt/sources.list.d/nodesource.list; \
    apt-get -y update; \
    apt-get -y install nodejs;
#RUN npm install libxmljs2; \
#    npm update --global npm
RUN apt-get -y install python3-pip; \
    pip install -r requirements.txt; \
    rm -f requirements.txt

WORKDIR /iptv/
COPY wrapper_v24.sh .
RUN ["chmod", "+x", "wrapper_v24.sh"]
RUN git clone --depth 1 -b master https://github.com/iptv-org/epg.git

WORKDIR /iptv/epg/
# permit max RAM of 1024 MiB on Raspberry Pi 4
ARG MAX_OLD_SPACE_SIZE=1024
ENV NODE_OPTIONS="--max_old_space_size=${MAX_OLD_SPACE_SIZE}"
RUN npm install

ARG IPTV_URL
ARG EPG_CACHED
ARG DEBUG

ENV IPTV_URL=$IPTV_URL
ENV EPG_CACHED=$EPG_CACHED
ENV DEBUG=$DEBUG

WORKDIR /iptv/
CMD ["sh", "wrapper_v24.sh"]