# Comments on
# 1) build
# 2) run
# 3) update

#docker build -t kodi_all:0.1 -f Dockerfile_ubuntu_all .
# outside
#docker run -d -p 0.0.0.0:3003:3003 -p 0.0.0.0:3001:3000 --restart unless-stopped --name kodi_all \
#--env-file .env -v "$(pwd)"/src/data:/iptv/iptv/src/data kodi_all:0.1
##--add-host=host.docker.internal:host-gateway
# locally
##docker run -d -p 127.0.0.1:3003:3003 -p 127.0.0.1:3001:3000 --restart unless-stopped --name kodi_all \
#--env-file .env -v "$(pwd)"/src/data:/iptv/iptv/src/data kodi_all:0.1
# update guide regularly via
# docker exec -w <working dir> <container id | name> npm run grab -- --site=<web site>, e.g.
#docker exec -w /iptv/epg/scripts/commands/epg/ kodi_all npm run grab -- --site=chaines-tv.orange.fr
# crontab -e
#0 9,12,15,18 * * * docker exec -w /iptv/epg/scripts/commands/epg/ kodi_all npm run grab -- --site=chaines-tv.orange.fr

FROM ubuntu:22.04

# iptv service
WORKDIR /iptv/iptv/
COPY src/*.py src/
COPY requirements.txt .

RUN apt-get update; \
    apt-get -y upgrade
RUN apt-get -y install git; \
    apt-get -y install curl
RUN apt-get install -y ca-certificates libatomic1 gnupg; \
    mkdir -p /etc/apt/keyrings; \
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key \
     | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg; \
    NODE_MAJOR=20; \
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] \
    https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" \
     > /etc/apt/sources.list.d/nodesource.list; \
    apt-get -y update; \
    apt-get -y install nodejs; \
    npm update --global npm
RUN apt-get -y install python3-pip; \
    pip install -r requirements.txt; \
    rm -f requirements.txt

WORKDIR /iptv/
COPY wrapper.sh .
RUN ["chmod", "+x", "wrapper.sh"]
RUN git clone --depth 1 -b master https://github.com/iptv-org/epg.git

WORKDIR /iptv/epg/
# 1024 MiB on raspberry Pi 4
ARG MAX_OLD_SPACE_SIZE=1024
ENV NODE_OPTIONS="--max_old_space_size=${MAX_OLD_SPACE_SIZE}"
RUN npm install

ENV IPTV_URL=$IPTV_URL
ENV EPG_CACHED=$EPG_CACHED

WORKDIR /iptv/
CMD ./wrapper.sh